### ISSUE TITLE
/api/stacks error

### ISSUE THREAD

**Issue by zerebos** [LooLzzz/docking-station#28]
I was excited to see the issue with `docker.io` resolved so I tried updating (and ran into this issue) then removing everything and doing a clean install and still ran into this. The UI just shows the "but nobody came" placeholder, and the network requests shows an error response from `/api/stacks`

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/settings/cache.py", line 231, in inner
    ret = await ensure_async_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/settings/cache.py", line 136, in ensure_async_func
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/routes/stacks.py", line 29, in list_compose_stacks
    return await docker_services.list_compose_stacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 171, in list_compose_stacks
    stacks = await asyncio.gather(*[
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 163, in _task
    stack.services = await list_containers(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 68, in list_containers
    await asyncio.gather(*[
  File "/app/docking-station-app/src/app/api/services/docker.py", line 56, in _task
    res.image = await get_image(
                ^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 146, in get_image
    images = await list_images(
             ^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 132, in list_images
    images = await asyncio.gather(*[
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 107, in _task
    image_inspect = await get_image_inspect(image_remote_digest, no_cache=no_cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/regctl.py", line 97, in get_image_inspect
    return await _get_image_inspect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/settings/cache.py", line 202, in inner
    return return_type.model_validate(ret)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for RegctlImageInspect
  Input should be a valid dictionary or instance of RegctlImageInspect [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
```

and the raw api response:
```json
{"message":"RegctlImageInspect","traceback":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/usr/local/lib/python3.12/site-packages/starlette/routing.py\", line 72, in app\n    response = await func(request)\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/fastapi/routing.py\", line 278, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/fastapi/routing.py\", line 191, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/settings/cache.py\", line 231, in inner\n    ret = await ensure_async_func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/settings/cache.py\", line 136, in ensure_async_func\n    return await func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/routes/stacks.py\", line 29, in list_compose_stacks\n    return await docker_services.list_compose_stacks(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 171, in list_compose_stacks\n    stacks = await asyncio.gather(*[\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 163, in _task\n    stack.services = await list_containers(\n                     ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 68, in list_containers\n    await asyncio.gather(*[\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 56, in _task\n    res.image = await get_image(\n                ^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 146, in get_image\n    images = await list_images(\n             ^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 132, in list_images\n    images = await asyncio.gather(*[\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/docker.py\", line 107, in _task\n    image_inspect = await get_image_inspect(image_remote_digest, no_cache=no_cache)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/services/regctl.py\", line 97, in get_image_inspect\n    return await _get_image_inspect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/docking-station-app/src/app/api/settings/cache.py\", line 202, in inner\n    return return_type.model_validate(ret)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pydantic/main.py\", line 596, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npydantic_core._pydantic_core.ValidationError: 1 validation error for RegctlImageInspect\n  Input should be a valid dictionary or instance of RegctlImageInspect [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/model_type\n","errors":[{"type":"model_type","loc":[],"msg":"Input should be a valid dictionary or instance of RegctlImageInspect","input":null,"ctx":{"class_name":"RegctlImageInspect"},"url":"https://errors.pydantic.dev/2.9/v/model_type"}]}
```

Is there something I setup wrong? Or is this some issue with the actual app?

**Comment by LooLzzz** [comment]
Would you mind trying to delete `/app/data/cache.db`?
Try to clear cache in your browser as well.

This error should no happen because I have a `if ret is not None` check right before that 🤔

**Comment by zerebos** [comment]
Deleting the `cache.db` and restarting (a couple times) did fix it. But this happened with a fresh image and empty volume which is odd. I'll close the issue but something to keep an eye on I guess.

On a side note how do you disable the auto updater fully? I saw something along those lines in the release notes but the docker log is hundreds of thousands of lines saying `auto updater is disabled`

**Comment by LooLzzz** [comment]
Great hearing its working now.

About auto_updater -  
I've uploaded a hotfix #29

[v0.3.1](https://github.com/LooLzzz/docking-station/releases/tag/v0.3.1) should be ok now.  
Wait for the build to finish and give it a try.
