### ISSUE TITLE
Errors upon run

### ISSUE THREAD

**Issue by lockheed** [LooLzzz/docking-station#4]
Run in docker with docker-compose from the main page here.

```
[SERVER]     return await func(*args, **kwargs)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/routes/stacks.py", line 29, in list_compose_stacks
[SERVER]     return await docker_services.list_compose_stacks(
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 167, in list_compose_stacks
[SERVER]     stacks = await asyncio.gather(*[
[SERVER]              ^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 159, in _task
[SERVER]     stack.services = await list_containers(
[SERVER]                      ^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 68, in list_containers
[SERVER]     await asyncio.gather(*[
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 56, in _task
[SERVER]     res.image = await get_image(
[SERVER]                 ^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 147, in get_image
[SERVER]     raise KeyError(repository_or_tag)
[SERVER] KeyError: 'tensorchord/pgvecto-rs:pg14-v0.2.0'
[SERVER] INFO:     regctl image inspect response: 2023-05-16 22:55:59.516236+00:00
[SERVER] INFO:     regctl image inspect response: 2021-04-24 00:36:05.321343+00:00
[SERVER] INFO:     regctl image inspect response: 2024-07-07 22:11:54.148247+00:00
[SERVER] INFO:     regctl image inspect response: 2024-07-02 04:49:11.769011+00:00
[SERVER] INFO:     regctl image inspect response: 2024-05-23 05:46:30+00:00
[SERVER] INFO:     regctl image inspect response: 2024-06-03 06:58:58.546605+00:00
[SERVER] INFO:     regctl image inspect response: 2024-07-15 18:43:15.282512+00:00
[SERVER] INFO:     regctl image inspect response: 2024-06-11 02:37:24+00:00
[SERVER] INFO:     regctl image inspect response: 2024-06-10 08:50:51.316992+00:00
[SERVER] INFO:     regctl image inspect response: 2023-11-11 18:51:37.413006+00:00
[SERVER] INFO:     regctl image inspect response: 2021-01-17 08:13:25.503291+00:00
[SERVER] INFO:     regctl image inspect response: 2024-04-25 07:29:47.887631+00:00
[SERVER] INFO:     127.0.0.1:53542 - "GET /api/stacks HTTP/1.1" 500
[SERVER] ERROR:    Exception in ASGI application
[SERVER] Traceback (most recent call last):
[SERVER]   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
[SERVER]     result = await app(  # type: ignore[func-returns-value]
[SERVER]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
[SERVER]     return await self.app(scope, receive, send)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
[SERVER]     await super().__call__(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
[SERVER]     await self.middleware_stack(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
[SERVER]     await self.app(scope, receive, _send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
[SERVER]     await self.app(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
[SERVER]     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[SERVER]     await app(scope, receive, sender)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
[SERVER]     await self.middleware_stack(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
[SERVER]     await route.handle(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
[SERVER]     await self.app(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
[SERVER]     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[SERVER]     await app(scope, receive, sender)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
[SERVER]     response = await func(request)
[SERVER]                ^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
[SERVER]     raw_response = await run_endpoint_function(
[SERVER]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
[SERVER]     return await dependant.call(**values)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/settings/cache.py", line 231, in inner
[SERVER]     ret = await ensure_async_func(*args, **kwargs)
[SERVER]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/settings/cache.py", line 136, in ensure_async_func
[SERVER]     return await func(*args, **kwargs)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/routes/stacks.py", line 29, in list_compose_stacks
[SERVER]     return await docker_services.list_compose_stacks(
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 167, in list_compose_stacks
[SERVER]     stacks = await asyncio.gather(*[
[SERVER]              ^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 159, in _task
[SERVER]     stack.services = await list_containers(
[SERVER]                      ^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 68, in list_containers
[SERVER]     await asyncio.gather(*[
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 56, in _task
[SERVER]     res.image = await get_image(
[SERVER]                 ^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 147, in get_image
[SERVER]     raise KeyError(repository_or_tag)
[SERVER] KeyError: 'tensorchord/pgvecto-rs:pg14-v0.2.0'
```

**Comment by LooLzzz** [comment]
Would you kindly share your compose files for
- `docking-station` 
- the service using `tensorchord/pgvecto-rs:pg14-v0.2.0` image

**Comment by fmorva** [comment]
I also got this error

```
[SERVER] ERROR:    Exception in ASGI application
[SERVER] Traceback (most recent call last):
[SERVER]   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
[SERVER]     result = await app(  # type: ignore[func-returns-value]
[SERVER]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
[SERVER]     return await self.app(scope, receive, send)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
[SERVER]     await super().__call__(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
[SERVER]     await self.middleware_stack(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
[SERVER]     await self.app(scope, receive, _send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
[SERVER]     await self.app(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
[SERVER]     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[SERVER]     await app(scope, receive, sender)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
[SERVER]     await self.middleware_stack(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
[SERVER]     await route.handle(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
[SERVER]     await self.app(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
[SERVER]     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[SERVER]     raise exc
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[SERVER]     await app(scope, receive, sender)
[SERVER]   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
[SERVER]     response = await func(request)
[SERVER]                ^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
[SERVER]     raw_response = await run_endpoint_function(
[SERVER]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
[SERVER]     return await dependant.call(**values)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/settings/cache.py", line 231, in inner
[SERVER]     ret = await ensure_async_func(*args, **kwargs)
[SERVER]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/settings/cache.py", line 136, in ensure_async_func
[SERVER]     return await func(*args, **kwargs)
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/routes/stacks.py", line 29, in list_compose_stacks
[SERVER]     return await docker_services.list_compose_stacks(
[SERVER]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 167, in list_compose_stacks
[SERVER]     stacks = await asyncio.gather(*[
[SERVER]              ^^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 159, in _task
[SERVER]     stack.services = await list_containers(
[SERVER]                      ^^^^^^^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 68, in list_containers
[SERVER]     await asyncio.gather(*[
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 56, in _task
[SERVER]     res.image = await get_image(
[SERVER]                 ^^^^^^^^^^^^^^^^
[SERVER]   File "/app/docking-station-app/src/app/api/services/docker.py", line 147, in get_image
[SERVER]     raise KeyError(repository_or_tag)
[SERVER] KeyError: 'docker.io/library/redis:7'
```

The service causing the error:
```
broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./appdata/paperless/redis:/data
      ```

**Comment by LooLzzz** [comment]
Moving all discussions regarding this to #7
