### ISSUE TITLE
"But nobody came" on 1 of 3 Proxmox VMs

### ISSUE THREAD

**Issue by gmsh-1** [LooLzzz/docking-station#57]
Possibly related to issue #55.

I have 3 Ubuntu VMs in Proxmox and running docking-station successfully on 2 of them. On the 3rd VM I am getting the "But nobody came". 

This is what is see in the log of the VM with the issue:

INFO:     2024-10-19 14:11:56 [uvicorn.access] 127.0.0.1:57256 - "GET /api/settings HTTP/1.1" 200
INFO:     2024-10-19 14:12:00 [uvicorn.access] 127.0.0.1:57268 - "GET /api/stacks HTTP/1.1" 500
ERROR:    2024-10-19 14:12:00 [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/settings/cache.py", line 231, in inner
    ret = await ensure_async_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/settings/cache.py", line 136, in ensure_async_func
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/routes/stacks.py", line 29, in list_compose_stacks
    return await docker_services.list_compose_stacks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 171, in list_compose_stacks
    stacks = await asyncio.gather(*[
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 163, in _task
    stack.services = await list_containers(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 68, in list_containers
    await asyncio.gather(*[
  File "/app/docking-station-app/src/app/api/services/docker.py", line 56, in _task
    res.image = await get_image(
                ^^^^^^^^^^^^^^^^
  File "/app/docking-station-app/src/app/api/services/docker.py", line 151, in get_image
    raise KeyError(repository_or_tag)
KeyError: 'linuxserver/mariadb:latest'

**Comment by gmsh-1** [comment]
Going through the closed issues, this might be related to #7 but there was a fix in 0.4 release as far as I can see.
My brain is fried, I have been trying to fix it for the last 3 hours :(

**Comment by LooLzzz** [comment]
Yep this `KeyError: '....'` is an issue that keeps coming back and I'm not entirely sure why..

Thank you for the logs

**Comment by LooLzzz** [comment]
Closing this in favor of #35
